#!/bin/bash

bingcc_incpath=`dirname $(readlink -f $0)`

source $bingcc_incpath/common-options.sh
source $bingcc_incpath/version-options.sh

gcc $bingcc_options -include "$bingcc_incpath/glibc_ver.h" $@ $bingcc_veropts
