#!/bin/bash

LIBCPATH="/lib/x86_64-linux-gnu/libc.so.6"
LIBC32PATH="/lib/i386-linux-gnu/libc.so.6"

if [ -z $1 ]
then
	libcver="2.3.6"
else
	libcver=$1
fi

#if [ -z $2 ]
#then
#	stdcppver="3.4.11"
#else
#	stdcppver=$2
#fi

echo "Generating files for glibc $libcver (native) ..."

./gensymoverride GLIBC "$libcver" $LIBCPATH > glibc_ver.h 

echo "Generating files for glibc $libcver (32-bit) ..."

./gensymoverride GLIBC "$libcver" $LIBC32PATH > glibc_ver32.h 

#echo "Generating files for libstdc++ $stdcppver ..."

#./gensymoverride GLIBCXX "$stdcppver" /lib/*.so.* /usr/lib/*.so.* > stdcpp_ver.h

echo "Done!"

